#if !canImport(ObjectiveC)
import XCTest

extension CaptureViewTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CaptureViewTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CaptureViewTests.__allTests__CaptureViewTests),
    ]
}
#endif
